"""One-time migration: filesystem JSON -> SQLite.

Reads the legacy JSON stores (Database/users.json, Database/collab.json, and
Database/ai.json) and populates the SQLite database managed by db.py.

Safe to re-run: existing rows are left untouched (guarded by primary key and
"only if not already present" checks), so it is idempotent.

Usage:
    python migrate_to_sqlite.py          # from the Backend directory
"""

import json
import os
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATABASE_DIR = os.path.join(BASE_DIR, "..", "Database")
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

import db


def _load_json(path):
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def migrate_users():
    data = _load_json(os.path.join(DATABASE_DIR, "users.json"))
    if not data:
        return 0
    count = 0
    for uid, u in data.items():
        if db.get_user(uid):
            continue  # already migrated
        courses = u.get("courses") or []
        db.create_user(uid, u.get("name", ""), u.get("email", ""), u.get("password", ""))
        db.update_user(uid, {
            "school": u.get("school"),
            "program": u.get("program"),
            "goals": u.get("goals"),
            "courses_json": json.dumps(courses),
            "onboarded": 1 if u.get("onboarded") else 0,
            "ai_model": u.get("ai_model"),
            "ai_level": u.get("ai_level"),
        })
        count += 1
    return count


def migrate_collab():
    data = _load_json(os.path.join(DATABASE_DIR, "collab.json"))
    if not data:
        return
    # memberships
    for slug, members in (data.get("memberships") or {}).items():
        for uid in members or []:
            db.add_member(slug, uid)
    # subject codes
    for slug, code in (data.get("subject_codes") or {}).items():
        if not db._query_one("SELECT 1 FROM subject_codes WHERE slug = ?", (slug,)):
            db._execute("INSERT INTO subject_codes (slug, code) VALUES (?, ?)", (slug, code))
    # materials
    for slug, items in (data.get("materials") or {}).items():
        for m in items or []:
            db.add_material(slug, m.get("filename", ""), m.get("uploader_id"))
    # quizzes
    for quiz_id, q in (data.get("quizzes") or {}).items():
        if db.get_quiz(quiz_id):
            continue
        db._execute(
            "INSERT INTO quizzes (id, subject, title, description, creator, invite_code, questions_json) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (quiz_id, q.get("subject"), q.get("title"), q.get("description"),
             q.get("creator"), q.get("invite_code"), json.dumps(q.get("questions", []))),
        )
    # attempts
    for a in data.get("attempts") or []:
        db.add_attempt(a.get("quiz_id"), a.get("user_id"), a.get("score"), a.get("total"))


def migrate_ai():
    data = _load_json(os.path.join(DATABASE_DIR, "ai.json"))
    if not data:
        return
    convs = data.get("conversations") or {}
    usage = data.get("usage") or {}
    for uid, per_user in convs.items():
        if db._query_one("SELECT 1 FROM ai_conversations WHERE user_id = ? LIMIT 1", (uid,)):
            continue  # already migrated
        for cid, c in per_user.items():
            db.ai_create_conversation(uid, title=c.get("title", "Conversation"),
                                      model=c.get("model", "claude"), mode=c.get("mode", "ask"))
            # The id generated by create_conversation differs; we keep the same
            # logical conversation by copying messages onto the new id.
            created = db.ai_get_conversation(uid, _latest_conv_id(uid, cid))
            if created:
                for m in c.get("messages", []):
                    db.ai_add_message(
                        uid, created["id"], m.get("role", "user"), m.get("content", ""),
                        model=m.get("model"), metadata=m.get("metadata"),
                    )
    for uid, u_usage in usage.items():
        db.ai_record_usage(uid, model=None, mode=None)  # placeholder; see below
        db._execute(
            "UPDATE ai_usage SET data_json = ? WHERE user_id = ?",
            (json.dumps(u_usage), uid),
        )


def _latest_conv_id(user_id, _legacy_cid):
    conn = db.connect()
    try:
        row = conn.execute(
            "SELECT id FROM ai_conversations WHERE user_id = ? ORDER BY rowid DESC LIMIT 1",
            (user_id,),
        ).fetchone()
        return row["id"] if row else None
    finally:
        conn.close()


def main():
    db.init_db()
    print("Migrating users ...")
    print(f"  users imported: {migrate_users()}")
    print("Migrating collaboration ...")
    migrate_collab()
    print("  collab imported.")
    print("Migrating AI data ...")
    migrate_ai()
    print("  ai imported.")
    print("Done. Database:", db.DB_PATH)


if __name__ == "__main__":
    main()