"""Mock AI provider for development and testing.

This provider is intentionally separate from real providers and clearly marked
so nobody mistakes it in production. It returns deterministic, helpful responses
so the full AI Learning Hub flow can be exercised without API credentials.

Set AI_PROVIDER=mock (or leave real API keys unset) to use it.
"""

import random
import re

from .base import AIProvider


class MockProvider(AIProvider):
    """A clearly-isolated fake provider. DO NOT use in a deployed environment."""

    is_mock = True
    name = "mock"

    def __init__(self, api_key=None):
        # Ignored; kept so the router can build every provider uniformly.
        self.api_key = None

    # Mode headings to make the demo response feel tailored to the task.
    _HEADINGS = {
        "explain": "Let's understand the concept",
        "summarize": "Here is a clear summary",
        "solve": "Let's work through the solution step by step",
        "quiz": "Here are practice questions to test yourself",
        "flashcards": "Here are study flashcards",
        "study_plan": "Here is a personalized study plan",
        "simplify": "Here is a simpler explanation",
        "exam_prep": "Here are exam-prep revision materials",
        "ask": "Here is an answer to your question",
    }

    def _response_for(self, mode_instruction, user_text, model):
        if not user_text:
            return "It looks like you didn't include a question. Try asking me something specific!"

        # Reflection of the user's topic for a natural-feeling reply.
        first_line = user_text.strip().splitlines()[0]
        snippet = first_line if len(first_line) <= 80 else first_line[:77] + "..."

        mode = mode_instruction
        heading = self._HEADINGS.get(mode, self._HEADINGS["ask"])
        header = f"{heading}: \"{snippet}\""
        body = (
            "\n\n*This is a demo response generated by the built-in mock provider, "
            "shown because no real AI API key is configured yet.*\n\n"
            "To start, the core idea and its key terms. "
            "Then break the explanation into clear numbered steps, include a "
            "concrete example and note one common mistake to avoid. "
            "Finally, check that you understand the *method* rather than just the answer."
        )
        steps = "\n\n1. State what the question is asking.\n2. Identify the relevant concept or formula.\n3. Work through it step by step, showing calculations.\n4. Verify the result makes sense."
        example = "\n\n**Example:** A worked, fully-explained example follows this pattern."

        return header + body + steps + example

    def generate(self, request):
        # Pull the last user message and any system prompt guidance.
        system = ""
        user_text = ""
        for m in request.get("messages", []):
            if m["role"] == "system":
                system = (system + " " + m["content"]).strip()
            elif m["role"] == "user":
                user_text = (user_text + "\n" + m["content"]).strip()

        mode = "explain"
        match = re.search(r"AI_MODE[:=]\s*(\w+)", system or "")
        if match:
            mode = match.group(1)

        content = self._response_for(mode, user_text, request.get("model"))
        return {
            "content": content,
            "usage": {"inputTokens": 0, "outputTokens": 0},
            "provider": self.name,
        }

    def stream(self, request):
        result = self.generate(request)
        # Yield in small chunks to simulate progressive streaming.
        chunk = 24
        text = result["content"]
        for i in range(0, len(text), chunk):
            yield text[i:i + chunk]

    def verify(self, api_key=None):
        """The mock always "accepts" keys so the demo flow never blocks."""
        return True, "Mock provider"
